stages:
  - prepare
  - audit
  - lint
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "17.0"
    file: '/npm/install-js-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "17.0"
    file: '/npm/audit.yml'
  - project: 'intern/runner-templates'
    ref: "17.0"
    file: '/npm/eslint.yml'

publish-pkg:
  stage: publish
  image: node:20.20.0-alpine
  resource_group: $CI_JOB_NAME
  needs:
    - install-js-dependencies
  cache:
    key:
      files:
        - package-lock.json
      prefix: ${CI_PROJECT_PATH_SLUG}_npm
    paths:
      - node_modules/
    policy: pull
  script:
    - echo "//${NPM_REGISTRY}/:username=${NPM_USER}" >> .npmrc
    - echo "//${NPM_REGISTRY}/:_password=$(echo -n ${NPM_PASS} | base64)" >> .npmrc
    - echo "email=${NPM_EMAIL}" >> .npmrc
    - echo "always-auth=true" >> .npmrc
    - npm version --new-version ${CI_COMMIT_TAG} --no-git-tag-version
    - npm publish
  after_script:
    - rm .npmrc
  tags:
    - docker
  only:
    - tags
