stages:
  - prepare
  - audit
  - lint

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: '17.3'
    file: '/npm/install-js-dependencies.yml'
  # Audit
  - project: 'intern/runner-templates'
    ref: '17.3'
    file: '/npm/audit.yml'
  # Lint
  - project: 'intern/runner-templates'
    ref: '17.3'
    file: '/npm/eslint.yml'
