import {ZigBeeDevice} from 'homey-zigbeedriver';
import {Cluster, CLUSTER, ZCLNode} from 'zigbee-clusters';
import mapValueRange from '../lib/helper/valueRange';
import {readInitialValue} from '../lib/attributeDevice';

const UP_OPEN = 'upOpen';
const DOWN_CLOSE = 'downClose';
const LIFT_PERCENTAGE = 'currentPositionLiftPercentage';

const SET_CAPABILITY = 'windowcoverings_set';
const STATE_CAPABILITY = 'windowcoverings_state';
const SET_TILT_CAPABILITY = 'windowcoverings_tilt_set';
const CLUSTER_SPEC = CLUSTER.WINDOW_COVERING;
const REPORT_DEBOUNCE_TIME = 5000;

const STATE_COMMAND_MAP = {
  up: 'upOpen',
  idle: 'stop',
  down: 'downClose',
};

export interface WindowCoveringsProperties {
  positionPercentageDebounce?: NodeJS.Timeout | null;
  positionPercentageDebounceEnabled?: boolean;
}

export interface ZigbeeWindowCoveringsDevice extends ZigBeeDevice, WindowCoveringsProperties {
}

export type WindowCoveringsCluster = Cluster & {
  upOpen: () => Promise<void>;
  downClose: () => Promise<void>;
  stop: () => Promise<void>;
};

export default async function initWindowCoveringsDevice(
  device: ZigbeeWindowCoveringsDevice,
  zclNode: ZCLNode,
  endpointId?: number,
): Promise<void> {
  if (!device.hasCapability(SET_CAPABILITY)) {
    return;
  }

  device.log(`Initialising ${SET_CAPABILITY} capability`);

  const endpoint = endpointId ?? device.getClusterEndpoint(CLUSTER_SPEC) ?? 1;
  const cluster = zclNode
    .endpoints[endpoint]
    .clusters[CLUSTER_SPEC.NAME] as unknown as WindowCoveringsCluster;

  const setParser = async function (value: number): Promise<unknown> {
    device.debug(`Newly set value for ${SET_CAPABILITY}`, value);

    // Refresh timer or set new timer to prevent reports from updating the dim slider directly
    // when set command from Homey
    if (device.positionPercentageDebounce) {
      device.positionPercentageDebounce.refresh();
    } else {
      device.positionPercentageDebounce = device.homey.setTimeout(() => {
        device.positionPercentageDebounceEnabled = false;
        device.positionPercentageDebounce = null;
      }, REPORT_DEBOUNCE_TIME);
    }

    // Used to check if reports are generated based on set command from Homey
    device.positionPercentageDebounceEnabled = true;

    // Override goToLiftPercentage to enforce blind to open/close completely
    if (value === 0 || value === 1) {
      const windowCoveringCommand = value === 1 ? UP_OPEN : DOWN_CLOSE;
      device.debug(`set → \`windowcoverings_set\`: ${value} → setParser → ${windowCoveringCommand}`);

      await cluster[windowCoveringCommand]();

      await device.setCapabilityValue('windowcoverings_set', value);

      return null;
    }

    const mappedValue = mapValueRange(0, 1, 0, 100, value);
    const gotToLiftPercentageCommand = {
      // Round, otherwise might not be accepted by device
      percentageLiftValue: Math.round(mappedValue),
    };
    device.debug(`set → \`${SET_CAPABILITY}\`: ${value} → setParser → goToLiftPercentage`, gotToLiftPercentageCommand);

    // Send command
    return gotToLiftPercentageCommand;
  };

  const reportParser = function (value: number): number | null {
    device.debug(`Newly reported value for ${SET_CAPABILITY}`, value);

    // Validate input
    if (value < 0 || value > 100) {
      return null;
    }

    // Parse input value
    const parsedValue = mapValueRange(0, 100, 0, 1, value);

    // Refresh timer if needed
    if (device.positionPercentageDebounce) {
      device.positionPercentageDebounce.refresh();
    }

    // If reports are not generated by set command from Homey update directly
    if (!device.positionPercentageDebounceEnabled) {
      return parsedValue;
    }

    // Return default
    return null;
  };

  // Retrieve initial values
  await readInitialValue(device, zclNode, SET_CAPABILITY, CLUSTER_SPEC, LIFT_PERCENTAGE, reportParser, endpoint);

  // Configure the capability
  device.registerCapability(SET_CAPABILITY, CLUSTER_SPEC, {
    endpoint,
    getOpts: {
      getOnStart: false,
    },
    get: 'currentPositionLiftPercentage',
    set: 'goToLiftPercentage',
    setParser,
    report: 'currentPositionLiftPercentage',
    reportParser,
  });

  device.log(`Initialised ${SET_CAPABILITY} capability`);

  // Check for state support, if so
  if (device.hasCapability(STATE_CAPABILITY)) {
    device.log(`Initialising ${STATE_CAPABILITY} capability`);

    device.registerCapability(STATE_CAPABILITY, CLUSTER_SPEC, {
      endpoint,
      set: (value: keyof typeof STATE_COMMAND_MAP) => STATE_COMMAND_MAP[value],
      setParser: () => ({}),
    });

    device.log(`Initialised ${STATE_CAPABILITY} capability`);
  }

  // Check for tilt support, if so
  if (device.hasCapability(SET_TILT_CAPABILITY)) {
    device.log(`Initialising ${SET_TILT_CAPABILITY} capability`);

    device.registerCapability(SET_TILT_CAPABILITY, CLUSTER_SPEC, {
      endpoint,
      getOpts: {
        getOnStart: false,
      },
      get: 'currentPositionTiltPercentage',
      set: 'goToTiltPercentage',
      setParser: value => ({
        percentageTiltValue: value * 100,
      }),
      report: 'currentPositionTiltPercentage',
      reportParser: value => value / 100,
    });

    device.log(`Initialised ${SET_TILT_CAPABILITY} capability`);
  }
}
